package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sioakim/attestward/internal/mapping"
	"github.com/sioakim/attestward/mappings"
)

var attestCmd = &cobra.Command{
	Use:   "attest",
	Short: "Manage self-attestation answers for controls attestor can't verify via API",
}

var attestInitOut string

var attestInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a commented self-attestation answers template",
	Long: `attest init writes a YAML template with one entry per question in
mappings/self-attestation-questions.yaml, each preceded by a comment giving
the question text and how to answer it. Fill in the answer: fields (leaving
one blank is fine — attestor scan reports that question not-checkable, never
assumed), then pass the file to attestor scan --self-attestation-file.`,
	RunE: runAttestInit,
}

func init() {
	attestInitCmd.Flags().StringVar(&attestInitOut, "out", "self-attestation.yaml", "output path for the generated template")
	attestCmd.AddCommand(attestInitCmd)
	rootCmd.AddCommand(attestCmd)
}

func runAttestInit(cmd *cobra.Command, _ []string) error {
	ssdf, err := mapping.LoadSSDFFS(mappings.FS, "ssdf-800-218.yaml")
	if err != nil {
		return fmt.Errorf("load ssdf mapping: %w", err)
	}
	questions, err := mapping.LoadSelfAttestationQuestionsFS(mappings.FS, "self-attestation-questions.yaml", ssdf)
	if err != nil {
		return fmt.Errorf("load self-attestation questions: %w", err)
	}

	if err := os.WriteFile(attestInitOut, renderAttestTemplate(questions), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", attestInitOut, err)
	}
	logf(cmd.OutOrStdout(), "wrote %s (%d question(s))\n", attestInitOut, len(questions.Questions))
	return nil
}

// renderAttestTemplate builds the answers-file template as raw bytes
// rather than via yaml.Marshal: a marshaled struct can't carry the
// per-question comments (question text, answer_type, evidence_prompt)
// that make the template usable without cross-referencing
// self-attestation-questions.yaml by hand, and the structure this
// produces (a "questions_version" key plus an "answers" list of
// id/answer/evidence_ref/attested_by/date maps) must exactly match what
// LoadSelfAttestationAnswers parses — locked in by
// TestRunAttestInit_OutputParsesBackCleanly and a golden-file test.
func renderAttestTemplate(questions *mapping.SelfAttestationQuestions) []byte {
	var b strings.Builder
	b.WriteString("# Self-attestation answers for attestor (generated by `attestor attest init`).\n")
	b.WriteString("#\n")
	b.WriteString("# Fill in each `answer:` field below. Leaving one blank is fine — an\n")
	b.WriteString("# unanswered question always reports not-checkable on the next scan, never\n")
	b.WriteString("# assumed. See mappings/self-attestation-questions.yaml (version ")
	b.WriteString(questions.Version)
	b.WriteString(") for\n")
	b.WriteString("# the full question set this file is a template of.\n")
	b.WriteString("\n")
	b.WriteString("questions_version: \"")
	b.WriteString(questions.Version)
	b.WriteString("\"\n")
	b.WriteString("answers:\n")

	for _, q := range questions.Questions {
		b.WriteString("  - id: ")
		b.WriteString(q.ID)
		b.WriteString("\n")
		b.WriteString("    # ")
		b.WriteString(q.Question)
		b.WriteString("\n")
		b.WriteString("    # answer_type: ")
		b.WriteString(q.AnswerType)
		if q.AnswerType == "yes_no" || q.AnswerType == "yes_no_evidence" {
			b.WriteString(" -- answer must be \"yes\" or \"no\"")
		}
		b.WriteString("\n")
		if q.EvidencePrompt != "" {
			b.WriteString("    # evidence_prompt: ")
			b.WriteString(q.EvidencePrompt)
			b.WriteString("\n")
		}
		b.WriteString("    answer: \"\"\n")
		b.WriteString("    evidence_ref: \"\"\n")
		b.WriteString("    attested_by: \"\"\n")
		b.WriteString("    date: \"\"\n")
		b.WriteString("\n")
	}

	return []byte(b.String())
}
